baseurl = "http://www.ajoshp.com"
title = "Josh Polansky"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "yourdiscussshortname"

[params]
  author = "Josh Polansky"
  info = "Engineer and Magician"
  description = "Josh Polansky's personal website"
  keywords = "blog,developer,personal"
  gravatar = "me@ajoshp.com"

  favicon_32 = "/img/favicon-32x32.png"
  favicon_16 = "/img/favicon-16x16.png"

  since = 2019

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

  # customCSS = ["css/custom.css"]
  # customSCSS = ["scss/custom.scss"]
  # customJS = ["js/custom.js"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa fa-github fa-2x"
  weight = 1
  url = "https://github.com/joshpolansky/"

# Menu links
[[menu.main]]
  name = "Fun"
  weight = 1
  url  = "robots/"
[[menu.main]]
  name = "About"
  weight = 2
  url = "about/"